[build]
  command = "npm run build"
  publish = "dist"
  functions = "lambda"

[dev]
  command = "npm run serve"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200